<?php
/**
 * Created by PhpStorm.
 * User: antonio
 * Date: 10/11/17
 * Time: 20:59
 */

require_once ("pages.php");
require_once ("Forms/forms.php");

class UpdatePage extends MenuPage
{
    public $formClass;
    public $modelClass;
    public $pk;

    /**
     * UpdatePage constructor.
     * @param $formClass
     * @param $model
     * @param $pk
     */
    public function __construct($formClass, $modelClass, $pk)
    {
        $this->formClass = $formClass;
        $this->modelClass = $modelClass;
        $this->pk = $pk;
    }


    public function body()
    {
        parent::body(); // TODO: Change the autogenerated stub

        $realModel = ($this->modelClass)::get($this->pk);

        echo "<div class = 'container'>";
        echo "<br>";
        echo sprintf("<h2 class='teal-text lighten-2'>Editar %s</h2>", $this->modelClass);
        $form = new $this->formClass($realModel->initial, "update.php", "POST", $this->modelClass);
        $form->render();
        echo "</div>";
    }
}