<?php
/**
 * Created by PhpStorm.
 * User: antonio
 * Date: 10/11/17
 * Time: 20:59
 */

require_once (__DIR__."/pages.php");
require_once (__DIR__."/../Forms/forms.php");

class UpdatePage extends MenuPage
{
    public $formClass;
    public $modelClass;
    public $pk;
    public $success_url;
    /**
     * UpdatePage constructor.
     * @param $formClass
     * @param $model
     * @param $pk
     */
    public function __construct($formClass, $modelClass, $pk, $success_url)
    {
        $this->formClass = $formClass;
        $this->modelClass = $modelClass;
        $this->pk = $pk;
        $this->success_url = $success_url;
    }


    public function body()
    {
        parent::body(); // TODO: Change the autogenerated stub

        $realModel = ($this->modelClass)::get($this->pk);

        echo "<div class = 'container'>";
        echo "<br>";
        echo sprintf("<h2 class='teal-text lighten-2'>Editar %s</h2>", $this->modelClass);

        if(isset($realModel->initial['password']))
            $realModel->initial['password'] = '';
        $form = new $this->formClass($realModel->initial, "Actions/update.php", "POST", $this->modelClass, $this->success_url);
        $form->render();
        echo "</div>";
    }
}